#!/bin/bash

if [[ $# -eq 0 ]] ; then
    ext=".log"
else
    ext=".$1"
fi

grep Error *$ext
grep ERROR *$ext
grep error *$ext
grep Exception *$ext
grep AssertionError *$ext
grep "java.lang.RuntimeException:" *$ext
grep "java.lang.AssertionError:" *$ext
grep "Can't read file" *$ext
grep Warning *$ext
grep WARNING *$ext
grep warning *$ext
