#!/usr/bin/python
########################################################################################
#A little script to tell you how many rooted tree topologies are possible for a given
#number of species.
#
#Gregg Thomas, Fall 2014
########################################################################################

import sys, math

if len(sys.argv) < 2:

	num_rtrees = {};

	for x in range(1,21):
		n = float(x);
		if x == 1 or x == 2:
			num_rtrees[x] = 1;

		else:
			num_rtrees[x] = ((math.factorial(2.0*n - 3.0)) / (2.0**(n-2.0) * math.factorial(n-2.0)));

	print("==============================================================");
	print("Number of species\tNumber of rooted trees");
	for each in num_rtrees:
		print(each, "\t\t\t", int(num_rtrees[each]));
	print("==============================================================");

else:
	n = float(sys.argv[1]);

	num_rtrees = ((math.factorial(2.0*n - 3.0)) / (2.0**(n-2.0) * math.factorial(n-2.0)));

	print("For", int(n), "species there are", int(num_rtrees), "rooted trees.");
